import java.io.*;
import java.math.*;
import java.security.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public class Task3{
    private static final Sanner scanner=new Sanner(System.in);

    public static void main(String[] args){
        int N=scanner.nextInt();
        scanner.skip("(\r\n|[\n\r\u2028\u2029\u0085])?");

        scnner.close;
    }
}
